[package]
name = "pddl-to-rdf"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tree-sitter = "0.20.10"
oxigraph = "0.3.16"

[build-dependencies]
cc = "*"
